import { defineConfig } from "eslint/config";
import tseslint from "@electron-toolkit/eslint-config-ts";
import eslintConfigPrettier from "@electron-toolkit/eslint-config-prettier";
import eslintPluginReact from "eslint-plugin-react";
import eslintPluginReactHooks from "eslint-plugin-react-hooks";
import eslintPluginReactRefresh from "eslint-plugin-react-refresh";

export default defineConfig(
  // src/renderer/src/components/ui is generated by the shadcn CLI and is
  // regenerated verbatim by `shadcn add`. Linting it only produces churn.
  {
    ignores: ["**/node_modules", "**/dist", "**/out", "src/renderer/src/components/ui/**"],
  },
  tseslint.configs.recommended,
  eslintPluginReact.configs.flat.recommended,
  eslintPluginReact.configs.flat["jsx-runtime"],
  {
    settings: {
      react: {
        version: "detect",
      },
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      "react-hooks": eslintPluginReactHooks,
      "react-refresh": eslintPluginReactRefresh,
    },
    rules: {
      ...eslintPluginReactHooks.configs.recommended.rules,
      ...eslintPluginReactRefresh.configs.vite.rules,
      "sort-imports": "error",
    },
  },
  // The renderer never constructs paths with Node's `path`, which cannot tell a
  // remote path from a local one. Use @shared/paths (localPath / remotePath).
  {
    files: ["src/renderer/**/*.{ts,tsx}"],
    rules: {
      "sort-imports": "error",
      "no-restricted-imports": [
        "error",
        {
          paths: ["path", "node:path", "path/posix"].map((name) => ({
            name,
            message: "Renderer code must use localPath/remotePath from @shared/paths instead.",
          })),
        },
      ],
    },
  },
  eslintConfigPrettier,
);
